# Generated by Django 3.1.7 on 2021-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favlinks', '0002_auto_20210402_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='links',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='links',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='is_authorised',
            field=models.BooleanField(default=False),
        ),
    ]
